### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hafriis** [hafriis/ewoms#1]
Next steps:

- [ ] DGF parser in PolyhedralGrid 
- [ ] finish test case co2injectionVE
- [ ] Implementation of integrated intensive quantities

**Comment by dr-robertk** [comment]
TODO2 (week 18) 
- [x] DGF parser in PolyhedralGrid is implemented (topsurf implemented)
- [x] Update all opm repositories, normally 'git fetch upstream' followed by 'git pull upstream/master' followed by 'git push origin master'
- [x] In opm-grid merge pull request (PR) by klicking merge button
- [x] check branch with 'git branch -a'
- [x] In ewoms 'git fetch upstream' and 'git rebase upstream/master'
if ouptut is 'Secuessfully ...' then ok, otherwise If something goes wrong you can cancel with 'git rebase --abort'. Finally, 'git push' 
- [x] finish test case co2injectionVE 
- [x] visualize test with ParaView, check VerteqGrid.
- [x] Study git functionality

Next steps:
- [ ] Check embedding of grids, 2D in 3D or vice versa
- [ ] Implementation of integrated intensive quantities in problem class in co2injectionproblemVE.hh 
- [ ] Iterating through column of 3D grid?
- [ ] Interaction between 2D and 3D grid in eWoms
- [ ] Check Cartesian coordinate in topsurf grid for mapping between 2D and 3D grid.
